### ISSUE TITLE
No preview images when using the search

### ISSUE THREAD

**Issue by dioncodes** [elrumo/macOS_Big_Sur_icons_replacements#1025]
### Describe your issue here, and if possible, add an image.
When a search keyword is entered and the grid is updated, the preview images aren't loading. (Tested in Safari and Chrome)
This is 100% reproducable and always happens when using the search:

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/1241360/103411205-09097580-4b6f-11eb-8491-82691e10b6f5.png">

**Comment by onodera-punpun** [comment]
Same for me, on both safari and safari preview. It only happens after searching and seems to me to be related to the use of a base64 image, which explains why It does work before searching.

**Comment by Owpac** [comment]
Same for me with Firefox.

**Comment by MichaelDevC** [comment]
Same for me on Chrome and Safari

**Comment by MichaelDevC** [comment]
I've inspected the site and there a lot of error relating to SSL Certificate!

![Screen Shot 2021-01-03 at 18 58 36](https://user-images.githubusercontent.com/57275048/103485361-05d3eb00-4df6-11eb-9c91-899f4dd66f82.png)

**Comment by crysxd** [comment]
I also can't download anything, guess it's the same issue!

**Comment by MichaelDevC** [comment]
> I also can't download anything, guess it's the same issue!

I really think that the SSL Certificate is expired and now we can't access to download and preview icons servers...

**Comment by crysxd** [comment]
Nah, it's just that the icons are coming from `http://82.145.63.160:1337` but the site itself is using HTTPS. Chrome doesn't like unencrypted connections on a secure page. The icons need to be hosted with HTTPS as well

**Comment by elrumo** [comment]
Last month the guys at fosshost.org offered me a free VPS hosting and I spent the last few weeks migrating all the icons and backend logic from Firebase to the new host running Parse Server. It took me some time, but that issue was present while I was adding the SSL certificate to the new server. Most icons are now served over SSL, but there are a bunch of icons that still use the IP address instead of the secure domain which I hope to get sorted within the next few days.

**Comment by elrumo** [comment]
And the reason why it didn't work when searching is because the search makes use of Algolia which hadn't been updated with the new location of the icons. To fix it I've created a script that runs automatically and triggers every time a change is made to the icons database and updates the Algolia index with the new data, so it should all be working now :)

**Comment by MichaelDevC** [comment]
@elrumo I can confirm that Icons now are showed correctly ! Thanks to have fixed that issue ;)

Hope that prince will be large and bigger in future!

Nice Job

**Comment by dioncodes** [comment]
Works just fine again, thank you!
