### ISSUE TITLE
Meta icon link is dead

### ISSUE THREAD

**Issue by onodera-punpun** [elrumo/macOS_Big_Sur_icons_replacements#1141]
The following link is dead: https://media.macosicons.com/parse/files/macOSicons/5187ed22bfba654daaea2c53b939b8dc_1605440936564_Meta.icns

**Comment by H-111-di** [comment]
So as lots of other icon links.
Take PyCharm as example:
https://media.macosicons.com/parse/files/macOSicons/c45b2d1a59e0900e3855a02366a81ebe_1614797627342.icns
https://media.macosicons.com/parse/files/macOSicons/9a62fc4310a36f46fbe7a7966d6b027f_1611930875096.icns
https://media.macosicons.com/parse/files/macOSicons/e832bf126968c995b136c4fb4b6085ee_1608227055136_IntelliJ_PyCharm.icns
http://82.145.63.160:1337/parse/files/macOSicons/a8111c9a5cb04c2069929888bbe35cae_1608297658918_IntelliJ_PyCharm.icns
https://media.macosicons.com/parse/files/macOSicons/0c8db1ca0ce9a9b1741e061749708dec_1608297658918_IntelliJ_PyCharm_CE.icns
https://media.macosicons.com/parse/files/macOSicons/255e598d8b72cbb0f442bf3976a988dd_1608296579946_IntelliJ_PyCharm_CE.icns

These are all deadlinks and return with a 'File not found'.

Maybe they are working on the website and didn't update some of the links?(since it was down once)

**Comment by elrumo** [comment]
They're all most likely icons that were lost to the hack, not much I can do now other than hope they get reuploaded back to the site.
