### ISSUE TITLE
Really weird stuff

### ISSUE THREAD

**Issue by JDagsa** [elrumo/macOS_Big_Sur_icons_replacements#879]
### Describe your issue here, and if possible, add an image.

Issue 1: The number of icons is at 2097 as seen on the search bar, but on the "Click to download" text, it says 105.

*Note that it increases only when I load all the rest of the icons.*
![Screen Shot 2020-11-20 at 4 17 56 PM](https://user-images.githubusercontent.com/72021139/99776669-21d44380-2b4c-11eb-9f7c-1e3e081aa8c4.png)

Issue 2: Icon previews are slightly broken, and if you click on ones with no preview, icon doesn't download.

![Screen Shot 2020-11-20 at 4 20 36 PM](https://user-images.githubusercontent.com/72021139/99776831-68c23900-2b4c-11eb-93ef-ac58b374b0a3.png)
![Screen Shot 2020-11-20 at 4 20 47 PM](https://user-images.githubusercontent.com/72021139/99776808-6069fe00-2b4c-11eb-915b-44234befda22.png)

I viewed it in Safari (ver. 14.0.1) on my Mac (MacBook Air 11-inch Mid-2012, running patched macOS Big Sur 11.0.1 - Build 20B29).

Hoping it'd be fixed, also saw this in my iPhone (6s Plus, iOS 14.2 - Build 18B92) in Safari (ver. 14.0.1)

**Comment by JDagsa** [comment]
Reloaded after some hours, fixed the number.

![Screen Shot 2020-11-20 at 11 12 23 PM](https://user-images.githubusercontent.com/72021139/99815884-e48ca780-2b85-11eb-93a7-3fa38f6db25f.png)

Previews are still somewhat broken.
![Screen Shot 2020-11-20 at 11 14 01 PM](https://user-images.githubusercontent.com/72021139/99816025-1998fa00-2b86-11eb-9974-45b0254fbda3.png)
![Screen Shot 2020-11-20 at 11 14 22 PM](https://user-images.githubusercontent.com/72021139/99816066-261d5280-2b86-11eb-9d36-693f58b56fc1.png)

**Comment by mmykhaylov** [comment]
+ some dates are incorrectly showing 1970

**Comment by elrumo** [comment]
Yes, that was only a momentary issue while I was making some changes to the site so it loads a lot faster and searches are much more efficient. The reason why some icons do not have an image when you make a search is because there was a bug, which I already fixed, where it would show icons that had been submitted but not approved yet (so the low res png and the .incs file hadn't been created, hence why you couldn't download it). Now it will only display icons that have been approved.

**Comment by elrumo** [comment]
Hi @mmykhaylov, that's because before the current system all the icons were hosted on GitHub and we did not store information on when it was submitted. I'm fixing that, but it's a 100% manual process where I need to look at when the commit with the icon was made to GitHub and manually update it on the current database. I'll eventually get there, but it will take some time, another issue for that same reason is that some icons are wrongly accredited to me, which I'm also slowly working on fixing.
